### ISSUE TITLE
Crash in llvm::ConstantHoistingPass

### ISSUE THREAD

**Issue by delcypher** [abenkhadra/gosat#5]
When run on the following example `gosat` SEGFAULTs.

```
(set-logic QF_FP)
(set-info :smt-lib-version 2.0)
(set-info :category "crafted")
(declare-fun x () (_ FloatingPoint 8 24))
(define-fun _t_10 () (_ FloatingPoint 8 24) (fp #b0 #b01111111 #b00000000000000000000001))
(define-fun _t_15 () Bool (fp.leq x _t_10))
(assert _t_15)
(assert (fp.isNaN x))
(check-sat)
```

The backtrace is as follows

```
#0  0x0000000000c81fda in llvm::ConstantHoistingPass::collectConstantCandidates(llvm::DenseMap<llvm::ConstantInt*, unsigned int, llvm::DenseMapInfo<llvm::ConstantInt*>, llvm::detail::DenseMa
pPair<llvm::ConstantInt*, unsigned int> >&, llvm::Instruction*) ()
#1  0x0000000000c82146 in llvm::ConstantHoistingPass::collectConstantCandidates(llvm::Function&) ()
#2  0x0000000000c821a9 in llvm::ConstantHoistingPass::runImpl(llvm::Function&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::BasicBlock&) ()
#3  0x0000000000ebe492 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
#4  0x0000000000ebe82b in llvm::FPPassManager::runOnModule(llvm::Module&) ()
#5  0x0000000000ebe0df in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
#6  0x00000000006b37d2 in llvm::MCJIT::emitObject(llvm::Module*) ()
#7  0x00000000006b3cb5 in llvm::MCJIT::generateCodeForModule(llvm::Module*) ()
#8  0x00000000006b0e64 in llvm::MCJIT::finalizeObject() ()
#9  0x00000000005deace in main (argc=3, argv=0x7fffffffe6a8) at /home/user/gosat/src/src/main.cpp:196
```

This is on Ubuntu 16.04LTS using the llvm 3.9 that ships with the distribution.

```
$ llvm-config-3.9 --version
3.9.1
```

**Comment by abenkhadra** [comment]
Handling this case is a bit tricky since reasoning in goSAT depends on executing the function. The problem here is that the condition below will always evaluate to `false` as the given constant is a `NaN`
```
(define-fun _t_15 () Bool (fp.leq x _t_10))
```
This is a corner case. Handling it in the distance function will unnecessarily slow things down. Therefore, I will come back to this later. Meanwhile, goSAT doesn't crash on this anymore.

**Comment by abenkhadra** [comment]
The constant in your example is not a `NaN`, my bad. Anyhow, this issue is now fixed.
